# Generated by Django 2.2.1 on 2019-09-24 10:57

import django.core.validators
from django.db import migrations, models
import student.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190610_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(), student.validators.validate_domainonly_email]),
        ),
    ]
